carpentries/styles

css/swc.css

This PR addresses #9.
* table cells had no padding, which caused a visual collapse (cell content was too close to cell neighbors)
* table header rows had dark blue background and black letters
* tables had no space between them and following paragraphs.
BEFORE:
* added 5px padding to cell contents
* changed header row background to gray-ish (I considered switching text color to white, but it didn't look good)
* 15px margin on the bottom of the tables (similarly to bottom margin used by paragraph style).
AFTER:

Fix: styles for tables in SQL lessons

---

css/swc.css

This solve the problem reported at https://github.com/swcarpentry/lesson-template/pull/200.

Fix background for lessons

---

css/swc.css

Address  #22 and  #21.
Figures should be centered
and not overflow the screen.
We need to duplicate Bootstrap rules because Pandoc AST tree doesn't support classes for images.

Improve figures

---

css/swc.css

**The screenshots are with zoom of 150% to make easy to see the differences.**
With Pandoc <= 1.13.2:
With Pandoc >= 1.14:
This pull request is a workaround to lessons have the same look of Pandoc <= 1.13.2 when built with Pandoc >= 1.14.

CSS compatible with different versions of Pandoc

---

bin/chunk-options.R

* use `.r` to style the code divs instead of `.source`
* remove extra line return in knitr output

Fix Rmd formatting

---

bin/generate_md_episodes.R

I had forgotten a little quirk of knitr that made the for loop fail. I'm using mapply with an anonymous function instead.

use anonymous function to generate markdown files

---

Makefile
bin/knit_lessons.sh

1.  Pass names of files to be built to `bin/knit_lessons.sh`.
2.  Only try to invoke `Rscript` if there are some files to knit.

Only try building R files if there are some

---

bin/generate_md_episodes.R

Implements the solution proposed by @noamross to check that all the packages required to build the lessons are available, and if they are not they get installed.

[fix # 82] Check R packages required by the lesson

---

_includes/episode_overview.html

`</br>` instead of `<br/>` renders fine in the browser but not in an epub

Fix "br" typo causing ugly rendering (epub only)

---

_layouts/base.html

The google site search box is currently not working because the javascript looks for the repository url in a `meta` tag "search-domain" being filled by jekyll variable `page.root` which returns only `.`. With github pages the correct repository url can be called with the variable `site.github.url`. This results in a correct google search that includes the operator like `site:http://swcarpentry.github.io/lesson-example`

fix search meta tag.

---

_includes/episode_navbar.html
_includes/navbar.html

Add label to search box and episode navigation arrows.
This pull fixes two accessibility issues:
1. To ensure the google search box can be understood by screen readers, added `aria-label` to the `input`. 
2. The navigation arrows at the top and bottom of episode pages were flagged for accessibility issues because they don't have any text, just a glyphicon. They are `<h3>` and `<a>`, both of which need some text or alternative label so that a screen reader can make sense of their purpose.
I fixed it by adding `aria-hidden="true"` to the glyphicons and an alternative text using bootstrap `.sr-only` class to the Liquid generating the elements.
These fixes remove the major flags in accessibility audit software, but I have not tested it with actual screen reader or other accessibility …

accessibility fixes.

---

assets/css/lesson.scss

Example of the problem: see "Ten Things You Need To Know" from http://swcarpentry.github.io/lesson-example/
For numbered lists that have more that 9 elements 1 em padding on the left is not sufficient. The result is that "1" in numbers "10" and above is printed on top of the border of encapsulating HTML block. 2 em padding solves this problem for lists with less that 100 elements. It should be safe to assume that numbered lists in Carpentries' lessons should not have more than 99 items.
This PR is related to: #115 and swcarpentry/lesson-example#83

lesson.scss: 2em left padding for lists

---

Makefile

The recipe for any phony target (e.g. `lesson-rmd`) will always run, so that's why bin/knit_lessons.sh was always executed as described in issue #91.
This PR introduces the logic that the Markdown files in `RMD_DST` are the prerequisites for a single `lesson-md` target, which is just a dummy grouping variable. The prerequisite for any one of RMD_DST is the original array of RMarkdown files (i.e. RMD_SRC). On systems that run make in parallel, the line `${RMD_DST} : ${RMD_SRC}` could cause bin/knit_lessons.sh to run for each member of RMD_DST. That would be bad, hence `.NOTPARALLEL`.

Knit episodes only when any one RMarkdown source changes

---

bin/lesson_initialize.py

The consumer was removed by 079d7d50 (#81).

bin/lesson_initialize.py: Remove 'example-site' reference

---

assets/css/lesson.scss

Change text color, background color and padding around inline code blocks.

Visually separate inline code blocks

---

_includes/javascript.html

Anchor links in the glossary do not currently work in any of the lessons. As @gvwilson mentions in https://github.com/swcarpentry/python-novice-inflammation/issues/305, if Github updates their version of kramdown in pages-gem this issue would be resolved. However, it is unclear when this merge will occur - https://github.com/github/pages-gem/pull/398
This is a workaround for now, and can potentially be removed when the kramdown version is updated in pages-gem
This issue was also mentioned in https://github.com/swcarpentry/python-novice-inflammation/pull/315

ensure dt elements have an id set

---

_includes/javascript.html

Reverts swcarpentry/styles#129 since the issue was fixed upstream.

Revert "ensure dt elements have an id set"

---

bin/generate_md_episodes.R

This is a follow up to #145, we ought to make sure that we are actually using the latest version of checkpoint before using the new name for the function.

make sure that checkpoint version is 0.4.0 or higher

---

_includes/navbar.html

At https://github.com/swcarpentry/styles/issues/155#issuecomment-313035185, @drjwbaker said
> We appear to have lost the icon graphic from all our lessons
This pull request fix this issue.
@k8hertweck We need to patch the lessons with this pull request before the release. Sorry for it.
cc @mkuzak

Fix logo at navbar

---

Makefile

make lesson-figures was generating figures out of episode order.  This appears to be due to a change in GNU Make. In older versions this returned values from $(wildcard) in sorted order; it no longer does so.  See https://stackoverflow.com/questions/40558385/gnu-make-wildcard-no-longer-gives-sorted-output-is-there-any-control-switch
This PR sorts the output of $(wildcard) so that episode figures appear in the correct order.

Output episode figures in correct order

---

bin/generate_md_episodes.R

Building `md` from `Rmd` in a script like this will break if the `methods` package is not called and the code includes class object routines. See https://github.com/r-spatial/sf/issues/478

Load methods package

---

_includes/episode_navbar.html

By doing this, when a page is heavily zoomed in (e.g. 500%) the navbar icons stay in the same row, rather than breaking onto two different rows. Also pulls the arrows to the outside of the row.
See also: https://github.com/carpentries/instructor-training/pull/521

Fix episode nav wrapping

---

assets/css/lesson.scss

Proposed usage:
<pre>when the user types a command and then presses *Enter*{:.keyboard} ...</pre>
The CSS is borrowed from StackExchange, which [implements this with the `<kbd>` tag][sx].
Block inline attribute lists are already used by SWC for e.g. the codeblocks, so I gather that this [span inline attribute list][sial] implementation is preferred over an HTML tag for SWC material.
SWC prefers verbose identifiers (`.objectives`, `.keypoints`, &etc), so I think `{:.keyboard}` would be preferred over `{:.kbd}`.
In practice it looks like this:
This would settle some confusion about how to format keyboard key names, such as swcarpentry/shell-novice#561.
[sx]: https://meta.stackexchange.com/questions/26207/how-can-i-format-as-keyboard-keys
[sial]: …

add keyboard key style

---

assets/css/lesson.scss

As reported at https://github.com/swcarpentry/lesson-example/issues/169 by @ErinBecker, the boxes with highlight code doesn't have the same colour as before. This will fix it.

Fix CSS to use .language-X class

---

bin/lesson_initialize.py

Clarified instructions for using GitHub to contribute, altered link for [issues] to direct to GitHub page on navigating issues to avoid FIXME issue with link when initializing, removed link to master repo to avoid FIXME issue with link when initializing.
These suggestions were based on a pull request initially done elsewhere https://github.com/swcarpentry/shell-novice/pull/639

Updated lesson_initialize

---

_includes/workshop_footer.html

Copy of https://github.com/swcarpentry/workshop-template/pull/458/.
For reference, the steps that I used:
~~~
$ git remote add workshop git@github.com:jcoliver/workshop-template.git
$ git fetch workshop
$ git cherry-pick workshop/update-footer-copyright
$ git push origin gh-pages
~~~
Thanks very much to @jcoliver for the original pull request.

Add current year to copyright of workshop footer

---

_includes/lesson_footer.html

As reported in https://github.com/Carpentries-ES/shell-novice/pull/18#issuecomment-365535244 by @orchid00, the Contact link is broken.
This fix this.

Fix broken link for Contact

---

_includes/links.md

Rather than send to pages that are now redirected, send people to the canonical place for the info an skip the redirect.

Updating to handbook as canonical source for CoC

---

_layouts/base.html

there is a typo in the github metadata documentation. `site.github.url` doesn't exist and cause page building failures in some cases (I haven't been able to figure out which ones). But as indicated in the example (https://help.github.com/articles/repository-metadata-on-github-pages/#usage) the correct variable name is `site.github.html_url`.

fix github meta data

---

_includes/links.md

Title is pretty self explanatory: there is a duplicate line in `links.md` that causes `make lesson-check` to produce errors:
```bash
$ make lesson-check
_includes/links.md: Duplicate definition of URL https://carpentries.github.io/instructor-training/05-memory/ at line 7
_includes/links.md: Duplicate reference concept-maps at line 7
```

links.md: remove duplicate line

---

bin/util.py

`bin/util.py` uses Python 2 that raises `IOError` when file is not found. `FileNotFoundError` is for Python 3

bin/util.py: fix error handling for Python 2

---

Makefile
bin/lesson_check.py

To make `lesson-check` useful in PRs, it has to return non-zero status.
For now, I'm making `lesson-check-all` _permissive_, but this might change in the future.

lesson_check.py: Exit with a status of 1 if something was wrong

---

bin/lesson_check.py

Switching to `argparse` as `optparse` is deprecated.

lesson_check: switch to argparse

---

bin/lesson_check.py

Add missing docstring to `check_metadata_fields` method.

lesson_check: add missing docstring

---

bin/lesson_check.py

`get_val` should be a static method as it does not use `self` or `cls`

lesson_check: get_val is a static method

---

bin/repo_check.py

Use `argpase` instead of `optparse`.
Remove unused variable `source_dir`

repo_check: use argparse and remove unused variable

---

bin/lesson_check.py

Function should always return something.
Here, I'm making `create_checker` function return `NotImplemented` if no checker is created/found.

lesson_check: fix create_checker function

---

bin/util.py

Instead of calling `assert False`, print a message to standard error stream and return `NotImplemented`.

util.py: make functions return NotImplemented

---

bin/lesson_check.py
bin/util.py

With Python3 we no longer need to inherit from `object` because it is added behind the scenes.

Use Python3-style class declaration

---

bin/util.py

Remove unnecessary call to `super` in `Reporter`'s `__init__`.

Remove unnecessary super call

---

.gitignore
bin/boilerplate/_config.yml

Cover swcarpentry/styles#274
Thanks to @katrinleinweber and @fmichonneau.

Make Jekyll ignore .Rproj

---

Makefile

Make `lesson-check` invoke `lesson-fixme`
`lesson-fixme` rule does not return an error, so the exit status of `lesson-check` is not impacted

Run lesson-fixme from within lesson-check

---

Makefile

If Docker is installed, `make docker-serve` will download and start a Jekyll container to build and serve the site with hot reloading. This binds the Jekyll webserver to localhost:4000 for security.
JEKYLL_VERSION should be synced with https://pages.github.com/versions/

Makefile: add docker-serve target

---

_includes/links.md

Individual lessons may want to easily link to the various lesson overview pages. This PR bundles those link targets centrally.

links.md: add links to carpentries' lessons overview pages

---

bin/lesson_check.py

this is my first python contribution :grimacing: 
The goal is to make sure that Rmd file episodes include 
```yml
source: Rmd
```
such that the "improve this page" links work and the md files include the note that says that the file shouldn't be edited.
@rgaiacs @maxim-belkin feedback welcome

[fix carpentries/styles#273] check yml header of Rmd includes source

---

Makefile

Typo: `clear-rmd` ~> `clean-rmd`

Makefile: fix typo in clean-rmd rule

---

assets/css/lesson.scss

I find the different parts of the content of the callout boxes crowded. Attempting to give them a little more room.
Before:
After:

space out callout elements better

---

_includes/life_cycle.html
_layouts/base.html
assets/css/lesson.scss
assets/js/lesson.js
bin/boilerplate/_config.yml

in preparation for the release of the geospatial curriculum, we are piloting a life cycle indicator that will persist on top of the pages to indicate whether the lesson is in 'pre-alpha', 'alpha' or 'beta' stage.

add lesson life cycle stage indicator

---

Makefile
bin/generate_md_episodes.R
bin/knit_lessons.sh

This PR is a follow-on of [my comment](https://github.com/carpentries/styles/pull/153#issuecomment-401537578) on #153. The changes make it so that only Rmd files that have been changed are knit to md. They were motivated by the fact that the total time to build all the episodes of https://github.com/datacarpentry/r-raster-vector-geospatial is very long. This makes the existing setup difficult for local interactive development. The workflow would then be to call `make lesson-md` to build only the Rmds that have changed and `make -B lesson-md` to build all Rmds regardless of the `touch` stamp.

Only knit rmd files to md if they have changed

---

assets/css/lesson.scss
bin/boilerplate/_extras/figures.md

1. Fix the script so that all figures are displayed.
2. Add image numbers.
3. Don't add headers for episodes without images.
4. Add horizontal rulers to better separate adjacent images.
Don't add a ruler after the last image in the episode.
5. Add empty lines to improve code readability.
I'll add before and after screenshots later.

figures.md: fixes and improvements

---

bin/boilerplate/_extras/figures.md

Clone images instead of creating new document elements.
No visual changes are expected.
Should have a benefit of cloning alt.text / title, if any

Clone images instead of creating new ones

---

assets/css/lesson.scss

Setting `margin: 15px` causes all blocks (Prereq, code, etc) to be misaligned with the main text. 
This PR sets the left and right margins to 0.
Related commit: 80d6638a

Code/callout/prereq/etc blocks: set left and right margins to 0

---

bin/boilerplate/CONTRIBUTING.md

Remove repetitive text, add a white-space before parentheses in `The Carpentries(Software Carpentry, Data Carpentry, and Library Carpentry)`

CONTRIBUTING.md: remove repetitive text

---

bin/knit_lessons.sh

I believe `generate_md_episodes.R` requires 2 inputs exactly...
ping @fmichonneau

knit_lessons.sh: require 2 inputs exactly

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

I see lots of contributions where none of this placeholder text has
been deleted, but also quite a lot where the first line has been deleted,
but the 'ext below' hasn't (exactly in accordance with the current
instructions).

Clarify wording of PR & issue templates

---

assets/css/lesson.scss

Use the same colors but apply 12.5% opacity.
Solution boxes use 30% opacity

Colorize all boxes

---

assets/css/lesson.scss

Tool called `tota11y` that @raynamharris mentioned in carpentries/styles#390 reports that contrast of our code elements is very low. This PR fixes this using the suggestion from that tool. Here, I'm not changing the gray background but rather darken the blue color used to display text.

Improve contrast of code elements

---

assets/css/bootstrap.css
assets/css/lesson.scss
assets/css/syntax.css

Prefix code blocks with language names

---

assets/css/bootstrap.css

Tota11y reports that links in our challenge blocks have a
contrast ratio of 4.29, which is lower than their minimum
of 4.5. This PR implements the suggestion that their tool
provides by changing the color or links from #337ab7 to #2876b5.

Fix contrast of links in challenge blocks

---

bin/boilerplate/README.md

This contribution adds reference to the web page of the lesson in the Carpentries and makes it easier for visitors who want to contribute to get familiar with the good first issue badge.
This adds a list of current maintainers to the README.md, as well.
This is inspired by the README of the https://github.com/swcarpentry/r-novice-inflammation
and tries to solve the
issues:
https://github.com/swcarpentry/r-novice-inflammation/issues/401
and
https://github.com/datacarpentry/R-ecology-lesson/issues/491
I accept contributions to improve this PR.

reference to the webpage of the lesson + goodfirst

---

bin/lesson_check.py

Avoid inconsistent grammar

---

bin/util.py

Urgent fix, see https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
@fmichonneau @rgaiacs

util.py: hot fix for YAML loader

---

_includes/links.md

Change `relative_page_root` to `relative_root_path`.
I'm not sure why I used `relative_page_root` instead of `relative_root_path` for lesson-setup... copy/paste typo?

links.md: fix lesson-setup link

---

bin/lesson_check.py

- Don't check metadata in `aio.md` (it no longer has to be empty due to
recent changes).
- Make `read_references` skip `{% include ... %}` lines

lesson-check: exclude aio.md, fix read_references

---

Makefile

https://pages.github.com/versions/ now reports 3.8.5 as the official jekyll version

bump docker-serve jekyll version

---

assets/css/bootstrap.css

1. Font size in callout (and other) blocks was recently changed to 17.5px which appears to look strange. In this pull request we inherit font size (from the parent)
2. Margins in keypoint boxes are -15px, resulting in slightly different offset from the left side when compared to the code blocks. By setting margin to -10px, we make offsets in keypoint boxes and code blocks identical.

Callout (and other) blocks: proper font size, margins

---

assets/css/lesson.scss

Resolves carpentries/styles#411
Resolves swcarpentry/r-novice-gapminder#522

Use darker purple for code blocks

---

.gitignore

See https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/#cache-all-the-things- & https://github.com/jekyll/jekyll/releases/tag/v4.0.0
It appears during `make site` & `make serve`.

Ignore Jekyll 4's cache

---

assets/css/bootstrap.css
assets/css/lesson.scss

add `blockquote p { padding-bottom: 1em; }` to show paragraph breaks in challenges and call-outs. maintainer discussion indicated that `1em` provided better clarity than `inherit`.
below is a screenshot showing the difference using the **LC Intro to Data** lesson for the example.

Blockquote paragraphs lack proper space

---

assets/css/bootstrap.css
assets/css/lesson.scss

When we updated bootstrap to 3.4.1 in 6e5cba2, we lost a few settings that we had previously made to `bootstrap.css`. In this PR I'm restoring some of those lost settings.
Others either appear to make no changes or make changes that should be discussed.
Changes explained:
* bootstrap.css
- restore 17.5px font in blockquote. We override it in `lesson.scss`
* lesson.scss
- override blockquote font-size
- disallow hyphens in `samp`
- set top & left margins in `dt` and `dd` elements, correspondingly (affects "References" page)
Settings omitted in this PR:
- `blockquote pre:last-child { margin-botton: 0; }` as it appears to not affect anything
- `code { color: inherit; }` & `pre { color: inherit; }` as combined they appear to change the default text color of code blocks to match that of the …

restore lost CSS settings

---

_includes/aio-script.md
_includes/all_keypoints.html
_includes/episode_navbar.html
_includes/manual_episode_order.html
_includes/navbar.html
_includes/syllabus.html
bin/boilerplate/_extras/figures.md

This is an implementation of manual episode ordering. It uses `episode_order` and `extras_order` array variables if they is defined in `_config.yml`. See the comment below: https://github.com/carpentries/styles/pull/437#issuecomment-536710306.

Manual ordering of episodes and extras

---

_includes/manual_episode_order.html

HTML comments end up in the generated HTML pages: they're not displayed by
the browsers but they're still present there. Liquid comments do not end up
in the generated HTML pages

Switch to Liquid comments

---

_includes/aio-script.md
_includes/episode_keypoints.html
_includes/episode_overview.html

instead of doing Javascript injection to generate the all in one page, I realized we could use a pure Jekyll approach.
I parameterized the "include" commands that generate the objective, questions, keypoints, so we can pass the values of each episode when generating the all in one page.
@carpentries/lesson-infrastructure-committee what do you think of this change?
@maxim-belkin I'd appreciate a double check to make sure it also works with manual episode ordering as I'm not too familiar yet with how this works.

use jekyll to generate all in one instead of Javascript

---

.github/FUNDING.yml

More info at https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository

Enable 'Sponsor' button on GitHub repos

---

.gitignore
Gemfile
Makefile
bin/boilerplate/_config.yml
bin/run-make-docker-serve.sh

@carpentries/lesson-infrastructure-committee please provide feedback on this.
- What do you think of including `bundle update` as part of the command that "make" or "serve" the site? including it reduces the chances of getting error messages for missing or outdated dependencies. It's needed with Docker. For Docker, we could use caching and mount the folder that stores the dependencies (https://github.com/envygeeks/jekyll-docker#usage-3) but this works best if the Maintainers (or lesson contributors) only use Docker other the permissions in the folders get messy and it leads to errors. I don't know if people tend to stick to one approach or mix both. (NB: the Docker image we use for Jekyll has bundler installed by default).
- At least on my system, I have to add `--host 0.0.0.0` to the …

use bundler to render lessons

---

Makefile

- Use Bash instead of sh.
- Don't include `commands.mk` at the very end.
I didn't find any repo using `commands.mk`. If there is one/some, we can
keep it.

Makefile: Specify shell. Don't include commands.mk

---

Makefile

We removed executable permission bits from all Python scripts
so we have to use Python to execute them

Makefile: use Python to execute repo_check.py

---

Makefile

Rewrote `commands` target (removed pipe from it) -- tested on macOS and Windows.
Also, added `*` to target names and Roman numerals to command categories

Makefile: improve commands target and commands categories

---

bin/boilerplate/.travis.yml

Closes #429
Related to #301
I updated the version of R per https://github.com/carpentries/styles/issues/429#issuecomment-531277441 and selected `xenial-cran35` to match the distribution being used to Travis CI.  The comment is for newcomers like me who are trying to figure out how the Travis CI tests relate to the deployment process.
I tested this in [this build](https://travis-ci.org/gitter-lab/ml-bio-workshop/builds/584647245)

Update R install in .travis.yml

---

assets/css/lesson.scss

Improve styling of tab panels on setup pages:
Before
After:

lesson.scss: style tab panels on setup pages
