carpentries/styles

- css/bootstrap/bootstrap.css
- css/swc.css
This PR accompanies swcarpentry/site#833 
it brings a variety of fixes and modifications to the CSS to match the modifications to the template brought by the upgrade to bootstrap 3.
> Update CSS to go with the SWC site template update

- css/swc.css
@jpallen [suggested in the past](https://github.com/swcarpentry/lesson-template/pull/145#issuecomment-71692557) that we use this to avoid the background from site and lessons.
> Add documentation about card class

- tools/catalog.py
Add a tool to list the CSS styles used in a set of documents.
> CSS cataloguing tool

- bin/lesson_check.py
- bin/util.py
- bin/workshop_check.py
> Converting to reporter

- _includes/all_keypoints.html
- _includes/episode_keypoints.html
- _includes/episode_overview.html
- _includes/syllabus.html
- assets/css/lesson.scss
- bin/lesson_check.py
Closes #40 (except Markdown in key questions isn't displayed at all on the home page).
> Markdownifying bullets

- _includes/javascript.html
Was lost in transition to new template.
> Adding Google Analytics code

- _includes/syllabus.html
Close https://github.com/swcarpentry/lesson-example/issues/66
> Add link to setup from schedule

- _includes/episode_navbar.html
This will make page builds faster and somewhat simpler to understand.
> Using page.previous and page.next for links instead of loop

- _includes/carpentries.html
- _includes/episode_keypoints.html
- _includes/javascript.html
- _includes/lesson_footer.html
- _includes/main_title.html
- _includes/navbar.html
- _includes/workshop_ad.html
- _includes/workshop_footer.html
Because if I've forgotten, other people won't understand either.
> Adding comments on purposes of include files

- _includes/carpentries.html
- _includes/workshop_footer.html
Adding mention of Library carpentry to blurbs about Carpentries and to standard workshop footer.
> Including mention of Library Carpentry in include files

- Makefile
- bin/lesson_check.py
1.  Assume links have been put in `_includes/links.md`.
2.  Check that in `bin/lesson_check.py`.
3.  Launch lesson checker appropriately from Makefile.
This has been tested in the example lesson.
> Checking consolidated links

- assets/css/bootstrap.css
Close https://github.com/swcarpentry/styles/issues/101.
> Make tables wider

- _includes/lesson_footer.html
Close https://github.com/swcarpentry/lesson-example/issues/106.
> Update copyright year with current year

- _includes/syllabus.html
See https://github.com/swcarpentry/lesson-example/pull/100.
> Numbering the lessons in the schedule

- _includes/syllabus.html
As suggested by @gcapes at https://github.com/swcarpentry/make-novice/pull/81#issuecomment-286360863.
> Improve wording on syllabus.html

- bin/generate_md_episodes.R
fix swcarpentry/lesson-example#118
> fix swcarpentry/lesson-example#118: use checkpoint::scanForPackages

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
I've been getting a significant number of questions from new instructors and instructor trainees about the lesson contribution process. Specifically, many trainees are worried that if their contributions aren't accepted they won't be able to qualify as instructors. Some are also worried or frustrated about not hearing back about their contributions for a while. I wanted to help communicate to contributors that the maintainers are volunteers who have many other time commitments and sometimes delay in reviewing PRs is inevitable, also that even if a specific contribution isn't incorporated, their input is still appreciated and welcome.
I'm hopeful that this language will help clarify the process and assuage some of these concerns, especially for new members of our community.
> Suggest template language

- CONDUCT.md
- _includes/links.md
Rebased of https://github.com/swcarpentry/lesson-example/pull/116/.
Thanks to @tracyteal.
> Updated CONDUCT.md

- assets/js/lesson.js
Related to https://github.com/swcarpentry/lesson-example/issues/113.
This is based on
https://github.com/swcarpentry/instructor-training/pull/437/files and
https://github.com/swcarpentry/instructor-training/pull/439/files,
both write by @ErinBecker.
> Make challenges and discussion visibles

- _includes/main_title.html
- _includes/navbar.html
- bin/lesson_initialize.py
This is based on https://github.com/swcarpentry/lesson-example/pull/127/.
> Add "Offline" Capable

- _includes/links.md
> Fix github-importer link

- _includes/links.md
> Fix concept-maps link

- _layouts/base.html
- assets/css/syntax.css
- bin/chunk-options.R
- bin/lesson_check.py
- bin/lesson_initialize.py
Work from @naught101 as [this pull request](https://github.com/swcarpentry/lesson-example/pull/144/files) after rebase and squash with some additional change.
> Syntax highlight

- LICENSE.md
- _includes/lc/syllabus.html
- _includes/links.md
- bin/lesson_initialize.py
as suggested in https://github.com/swcarpentry/git-novice/pull/452#issuecomment-353035014 :-)
> secure hyperlinks to pre-empt server-side HTTPS redirects

- _includes/links.md
Please see https://github.com/swcarpentry/lesson-example/pull/172.
> Related with lesson-example/pull/172

- CONDUCT.md
Fixes https://github.com/swcarpentry/styles/issues/212
> Remove out-of-date CoC language

- _includes/lc/intro.html
Just 1 `https` update, see diff.
> Link DOIs to preferred resolver

- bin/lesson_check.py
- bin/lesson_initialize.py
- bin/repo_check.py
- bin/test_lesson_check.py
- bin/util.py
- bin/workshop_check.py
> convert to py3.4 syntax, a few cleanups

- _includes/lesson_footer.html
- assets/css/lesson.scss
This ensure that we have some semantic on our HTML and leave the rendering to CSS.
> Clean footer HTML

- _layouts/base.html
Related with swcarpentry/styles#246.
> Fix search

- _includes/lesson_footer.html
- bin/lesson_initialize.py
Related with swcarpentry/lesson-example/193.
@fmichonneau or @ErinBecker I need your review on this one, **including the start year**.
> Fix Copyright information

- _includes/lesson_footer.html
- assets/css/lesson.scss
This might help maintainers to migrate to new version of the style.
@fmichonneau Could you review this?
> Add note about the version of the style

- bin/boilerplate/README.md
- bin/lesson_initialize.py
This is a revamp of swcarpentry/styles#248.
Thanks to Andy Boughton.
> Add README to bin/lesson_initialize.py

- assets/css/lesson.scss
Related with swcarpentry/styles#244
> Fix font size of h2 in call out box

- bin/util.py
Moving functions `pretty` and `key` out form the `pretty` function, thus making it simpler.
> utils.py: simplify report function

- bin/boilerplate/_config.yml
- bin/boilerplate/_extras/about.md
- bin/boilerplate/_extras/discuss.md
- bin/boilerplate/_extras/figures.md
- bin/boilerplate/_extras/guide.md
- bin/boilerplate/aio.md
- bin/boilerplate/index.md
- bin/boilerplate/reference.md
- bin/boilerplate/setup.md
Related with swcarpentry/lesson-example#206
> Remove root and layout from YAML for boilerplate

- Makefile
- bin/lesson_check.py
- bin/lesson_initialize.py
- bin/repo_check.py
- bin/test_lesson_check.py
- bin/util.py
- bin/workshop_check.py
Related to swcarpentry/styles#271
> Change shebang to Python3

- bin/boilerplate/_config.yml
See https://github.com/swcarpentry/styles/blob/0e0f2bf4e396419a46760d0add6af054cd1c512c/_includes/lesson_footer.html#L42 and https://github.com/swcarpentry/styles/blob/0e0f2bf4e396419a46760d0add6af054cd1c512c/_includes/workshop_footer.html#L22
> Match new usage of the email parameter

- .gitignore
Added .Rhistory and .Rdata files to be ignored
> gitIgnore for R

- CODE_OF_CONDUCT.md
Will also match https://raw.githubusercontent.com/swcarpentry/lesson-example/gh-pages/CONDUCT.md
> remove permalink that breaks asset includes

- bin/boilerplate/_episodes/01-introduction.md
- bin/boilerplate/_extras/about.md
- bin/boilerplate/_extras/discuss.md
- bin/boilerplate/_extras/figures.md
- bin/boilerplate/_extras/guide.md
Adding `links.md` to boilerplate files.
> Add links.md to files in boilerplate

- _includes/carpentries.html
Add a description for the Carpentries, and update the descriptions of SWC, DC and LC based on @weaverbel text provided in #311.
> [fix carpentries/styles#311] update descriptions of the carpentries

- _includes/carpentries.html
From discussions with @weaverbel @libcce and Executive Council, added about the discussion stage to the Library Carpentry description.
> added about the discussion stage to the LC description

- bin/boilerplate/_config.yml
related to carpentries/workshop-template#506
> fix survey link variables

- bin/boilerplate/_config.yml
add survey links to _config.yml boilerplate
> Add surveys

- _includes/lesson_footer.html
- assets/css/lesson.scss
- bin/boilerplate/_config.yml
Requested changes to carpentries/styles#325.
> Fix footer and copyright notice (v2)

- .editorconfig
- bin/lesson_check.py
Draft implementation of https://github.com/swcarpentry/styles/issues/131 's suggestion.
> Harmonise code style through .editorconfig

- bin/boilerplate/CONTRIBUTING.md
See diff & [apple.com/macos](https://www.apple.com/macos/) ;-)
> Reflect Apple's rebranding

- _includes/workshop_footer.html
Creating this PR against this repo as requested by @fmichonneau in https://github.com/carpentries/workshop-template/pull/541#issuecomment-428373161
> Fix https://github.com/carpentries/workshop-template/issues/540

- .github/ISSUE_TEMPLATE.md
See https://github.com/swcarpentry/r-novice-inflammation/issues/401 > 3.
> ISSUE_TEMPLATE.md: Nudge contributors to specify episodes unambigously

- _includes/links.md
CC @rgaiacs and @fmichonneau since these links were added by both of you in carpentries/lesson-example
> links.md: sync with downstream (lesson-example)

- bin/lesson_check.py
I think we should include `_config.yml` to the list of required files...
> lesson_check.py: require _config.yml too

- _includes/links.md
looks like these links should be helpful/useful for all lessons
> links.md: lesson-specific links

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Update PR and issues template

- assets/css/lesson.scss
See https://github.com/swcarpentry/git-novice/pull/662#issuecomment-499555724
CC @kekoziar @fmichonneau
> Use 1px borders: fix Google Chrome & Edge

- bin/chunk-options.R
- fix swcarpentry/r-novice-inflammation#436
> specify language based on engine

- bin/boilerplate/README.md
> Fix minor typo in README

- _includes/manual_episode_order.html
> manual_episode_order.html: fix typo in a comment

- assets/css/lesson.scss
- bin/chunk-options.R
proposed implementation for #454 
Preview:
@carpentries/lesson-infrastructure-committee what do you think? I'm happy to consider a different color scheme :art:
> add warning hook + CSS class for Rmd-based lessons

- _includes/links.md
> Update PyPI link
